### ISSUE TITLE
关于vue3 + element-plus的替换el前缀组件作者有实现嘛

### ISSUE THREAD

**Issue by chinbor** [JimFirst/change-element-ui-prefix-demo#1]

**Comment by JimFirst** [comment]
暂时没有，后续有计划。

**Comment by chinbor** [comment]
> 

好的，老哥，出来了我第一个投入使用！！！！

**Comment by superermiao** [comment]
Syntax Error: 'import' and 'export' may appear only with 'sourceType: "module"'用了这个之后出现这个错

**Comment by JimFirst** [comment]
> > 
> 
> 好的，老哥，出来了我第一个投入使用！！！！

扒拉了一下element-plus的源码，官方自己后续应该会支持

**Comment by JimFirst** [comment]
> Syntax Error: 'import' and 'export' may appear only with 'sourceType: "module"'用了这个之后出现这个错

这个你应该排查一下你的开发环境，node版本之类的

**Comment by JimFirst** [comment]
官方已支持
